name: Deploy to Debian Server

on:
  push:
    branches:
      - main   # ganti ke main jika perlu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Debian Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2121
          script: |
            sudo mkdir -p /var/www/udinmjs
            sudo chown -R $USER:www-data /var/www/udinmjs
            sudo chmod -R 755 /var/www/udinmjs

            cd /var/www/udinmjs

            if [ ! -d ".git" ]; then
              git clone https://github.com/aditha69/MJS_Project .
            else
              git pull origin main
            fi