name: Deploy to Nginx

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Debian Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2121
          script: |
            set -e

            echo"== Pindah ke /var/www =="
            cd /var/www

            echo"== Hapus folder sementara =="
            sudo rm -rf udinmjs_tmp

            echo"== Clone repo ke folder sementara =="
            sudo git clone https://github.com/aditha69/MJS_Project udinmjs_tmp

            echo"== Kosongkan folder web =="
            sudo rm -rf udinmjs/*

            echo"== Pindahkan hasil deploy =="
            sudo cp -r udinmjs_temp/* udinmjs/
    
            echo"== Set permission =="
            sudo chown -R www-data:www-data udinmjs
            sudo chmod -R 755 udinmjs

            echo"== Bersihkan =="
            sudo rm -rf udinmjs
            
            echo"== Reload Nginx =="
            sudo systemctl reload nginx
            
            echo"== Deploy Selesai =="