name: CI/CD Deploy to Debian

on:
  push:
    branches:
      - main   

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step (optional)
        run: |
          echo "No build process required"


  deploy:
    name: Deploy (CD)
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          if_key_exists: replace

      - name: Setup Known Hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p 2121 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy files with rsync
        run: |
          rsync -avz --delete \
          -e "ssh -p 2121 -o StrictHostKeyChecking=no" \
          --exclude=".git" \
          --exclude=".github" \
          --exclude="node_modules" \
          --exclude=".env" \
          ./ \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Post-deploy command (optional)
        run: |
          ssh -p 2121 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            echo "Deploy selesai di server"
          EOF
